#!/usr/bin/env python3
"""Builds src/font8x16.c: the 256 CP437 glyphs, 8x16, for the Windows
local window (src/wingui.c), from a raw IBM VGA font dump (4096 bytes:
256 glyphs x 16 rows, top row first, bit 7 = leftmost pixel).

That is the same IBM VGA ROM font SyncTERM, Moebius and PabloDraw draw
with, so the sysop's local window matches what callers see pixel for
pixel. (Debian console-setup's MIT-licensed VGA fonts were tried first:
their box-drawing lines sit a row lower than IBM's and some CP437 glyphs
are stand-ins, so art drawn locally wouldn't match the callers' screens.)

    python3 util/make_font.py [path/to/CP437.F16]
    (default: Moebius's app/fonts/ibm/CP437.F16)
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT = os.path.expanduser("~/moebius/app/fonts/ibm/CP437.F16")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
    data = open(src, "rb").read()
    if len(data) != 4096:
        raise SystemExit("%s: expected 4096 bytes (256 x 8x16), got %d" % (src, len(data)))
    lines = ["/* CP437 8x16 font for the Windows local window: the IBM VGA ROM font",
             "   (as used by SyncTERM, Moebius and PabloDraw). Generated by",
             "   util/make_font.py -- don't edit. */", "",
             "const unsigned char ad_font8x16[256][16] = {"]
    for code in range(256):
        g = data[code * 16:code * 16 + 16]
        lines.append("    {" + ",".join("0x%02X" % b for b in g) + "},  /* %02X */" % code)
    lines += ["};", ""]
    with open(os.path.join(ROOT, "src", "font8x16.c"), "w") as f:
        f.write("\n".join(lines))
    print("wrote src/font8x16.c from", src)


if __name__ == "__main__":
    main()
