/* Intro splash -- the art lives in splash_art.c (generated by
 * util/make_splash.py). Every row is positioned with CUP, never a
 * newline, so it can't trip SyncTERM's column-80 wrap, and it's
 * centered on whatever screen the caller has (80x24 up through 132x37
 * and bigger local windows). */
#include "../include/splash.h"
#include "../include/input.h"
#include "OpenDoor.h"
#include <stdio.h>

static void draw(const AdDoor *door) {
    int ox = (door->cols - AD_SPLASH_W) / 2, oy = (door->rows - AD_SPLASH_H) / 2, i;
    char cup[32];
    if (ox < 0) ox = 0;
    if (oy < 0) oy = 0;
    /* blink mode on purpose -- see util/make_splash.py's sgr() */
    ad_dout("\x1b[?33l\x1b[?35l\x1b[0m\x1b[2J");
    for (i = 0; i < AD_SPLASH_NROWS; i++) {
        snprintf(cup, sizeof(cup), "\x1b[%d;%dH", AD_SPLASH_ROWS[i].row + oy + 1,
                 AD_SPLASH_ROWS[i].col + ox + 1);
        ad_dout(cup);
        ad_dout(AD_SPLASH_ROWS[i].data);
    }
    ad_dout("\x1b[0m");
    /* park the cursor on the prompt line, out of the art's way */
    snprintf(cup, sizeof(cup), "\x1b[%d;%dH", oy + AD_SPLASH_H, ox + 1);
    ad_dout(cup);
}

int ad_splash_show(AdDoor *door) {
    for (;;) {
        AdKey k;
        draw(door);
        k = ad_input_get(door->local);
        if (k.kind == AD_KEY_HANGUP || k.kind == AD_KEY_CLOSE) return 0;
        if (k.kind == AD_KEY_RESIZE) {
            ad_door_query_size(door, &door->cols, &door->rows);
            continue;
        }
        /* the release half of a click on the splash isn't a new key */
        return 1;
    }
}
